# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cserver.proto\"\x08\n\x06\x65mptyz\"\x18\n\x06userID\x12\x0e\n\x06userID\x18\x01 \x01(\t\"#\n\x07userIDS\x12\x18\n\x07userIDS\x18\x01 \x03(\x0b\x32\x07.userID\"2\n\x07\x63hatMsg\x12\x0c\n\x04orig\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"$\n\x07\x61llMsgs\x12\x19\n\x07\x61llMsgs\x18\x01 \x03(\x0b\x32\x08.chatMsg\"\x1c\n\x0c\x63onfirmation\x12\x0c\n\x04\x63onf\x18\x01 \x01(\t2\xab\x01\n\nmsgService\x12\"\n\x07sendMsg\x12\x08.chatMsg\x1a\r.confirmation\x12\x1b\n\x06\x61skMsg\x12\x07.userID\x1a\x08.chatMsg\x12\x1d\n\x08getUsers\x12\x07.emptyz\x1a\x08.userIDS\x12\x1c\n\x08joinChat\x12\x07.userID\x1a\x07.userID\x12\x1f\n\ngetAllMsgs\x12\x07.userID\x1a\x08.allMsgsb\x06proto3')
)




_EMPTYZ = _descriptor.Descriptor(
  name='emptyz',
  full_name='emptyz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=24,
)


_USERID = _descriptor.Descriptor(
  name='userID',
  full_name='userID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='userID.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=50,
)


_USERIDS = _descriptor.Descriptor(
  name='userIDS',
  full_name='userIDS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userIDS', full_name='userIDS.userIDS', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=87,
)


_CHATMSG = _descriptor.Descriptor(
  name='chatMsg',
  full_name='chatMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orig', full_name='chatMsg.orig', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='chatMsg.dest', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='chatMsg.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=139,
)


_ALLMSGS = _descriptor.Descriptor(
  name='allMsgs',
  full_name='allMsgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allMsgs', full_name='allMsgs.allMsgs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=177,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='confirmation',
  full_name='confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conf', full_name='confirmation.conf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=207,
)

_USERIDS.fields_by_name['userIDS'].message_type = _USERID
_ALLMSGS.fields_by_name['allMsgs'].message_type = _CHATMSG
DESCRIPTOR.message_types_by_name['emptyz'] = _EMPTYZ
DESCRIPTOR.message_types_by_name['userID'] = _USERID
DESCRIPTOR.message_types_by_name['userIDS'] = _USERIDS
DESCRIPTOR.message_types_by_name['chatMsg'] = _CHATMSG
DESCRIPTOR.message_types_by_name['allMsgs'] = _ALLMSGS
DESCRIPTOR.message_types_by_name['confirmation'] = _CONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

emptyz = _reflection.GeneratedProtocolMessageType('emptyz', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYZ,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:emptyz)
  })
_sym_db.RegisterMessage(emptyz)

userID = _reflection.GeneratedProtocolMessageType('userID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:userID)
  })
_sym_db.RegisterMessage(userID)

userIDS = _reflection.GeneratedProtocolMessageType('userIDS', (_message.Message,), {
  'DESCRIPTOR' : _USERIDS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:userIDS)
  })
_sym_db.RegisterMessage(userIDS)

chatMsg = _reflection.GeneratedProtocolMessageType('chatMsg', (_message.Message,), {
  'DESCRIPTOR' : _CHATMSG,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:chatMsg)
  })
_sym_db.RegisterMessage(chatMsg)

allMsgs = _reflection.GeneratedProtocolMessageType('allMsgs', (_message.Message,), {
  'DESCRIPTOR' : _ALLMSGS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:allMsgs)
  })
_sym_db.RegisterMessage(allMsgs)

confirmation = _reflection.GeneratedProtocolMessageType('confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:confirmation)
  })
_sym_db.RegisterMessage(confirmation)



_MSGSERVICE = _descriptor.ServiceDescriptor(
  name='msgService',
  full_name='msgService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=210,
  serialized_end=381,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMsg',
    full_name='msgService.sendMsg',
    index=0,
    containing_service=None,
    input_type=_CHATMSG,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='askMsg',
    full_name='msgService.askMsg',
    index=1,
    containing_service=None,
    input_type=_USERID,
    output_type=_CHATMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getUsers',
    full_name='msgService.getUsers',
    index=2,
    containing_service=None,
    input_type=_EMPTYZ,
    output_type=_USERIDS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='joinChat',
    full_name='msgService.joinChat',
    index=3,
    containing_service=None,
    input_type=_USERID,
    output_type=_USERID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAllMsgs',
    full_name='msgService.getAllMsgs',
    index=4,
    containing_service=None,
    input_type=_USERID,
    output_type=_ALLMSGS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSGSERVICE)

DESCRIPTOR.services_by_name['msgService'] = _MSGSERVICE

# @@protoc_insertion_point(module_scope)
