FROM ubuntu

RUN apt-get update && \
    apt-get -y install sudo 

RUN sudo apt-get -y install python3-pip
RUN sudo apt-get install curl gnupg -y
RUN curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -
RUN sudo apt-get -y install apt-transport-https 
RUN sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list
RUN sudo apt-get update -y
RUN sudo apt-get install rabbitmq-server -y --fix-missing
RUN pip3 install pika
EXPOSE 4369 5671 5672 25672
WORKDIR /Tarea_2_SD/Ejercicio_2/