version: '3'

services:

  consumer:
    build: ./app
    environment:
      - DEBUG
    network_mode: host
    ports:
      - 6000-7000:8500
    volumes:
      - ./app/syntax:/syntax
    stdin_open: true
    tty: true
    command: client.py
    depends_on:
      - server

  server:
    build: ./app
    environment:
      - DEBUG
    network_mode: host
    ports:
      - 8500:8500
    volumes:
      - ./app/log.txt:/log.txt
      - ./app/syntax:/syntax
    stdin_open: true
    tty: true
    command: server.py
